### ISSUE TITLE
Romart file not available error 404

### ISSUE THREAD

**Issue by effgarces** [retro-esp32/RetroESP32#105]
The romart archive is no longer available, error 404.

Also, I can't find info on what the correct format should be. I already have romart from the go-play firmware, in .art format, but it seems to be ignored.

**Comment by 32teeth** [comment]
We never provided them
You need to create them yourselves

[You this tool we created](https://convert-image-to-rom-art.herokuapp.com/)

**Comment by effgarces** [comment]
I was following the directions over at https://github.com/retro-esp32/RetroESP32/wiki/Romart-Usage and the romart archive referred there is not available.

As for the tool yes I already checked/used it, the main isssue is that the romart archive from the go-play firmware seems to ignored and does not load. Does the romart for the retroesp32 needs something different than that format? The images are already in the art format and in their respective folders.

**Comment by 32teeth** [comment]
> See the release
I included the art and png files now

https://github.com/retro-esp32/RetroESP32/releases/tag/v.0.0-Box-Art-Archive
