### ISSUE TITLE
How to switch between internal DAC and I2S DAC

### ISSUE THREAD

**Issue by h1aji** [retro-esp32/RetroESP32#106]
I noticed that there is an option **ODROID_AUDIO_SINK_DAC** which allows to make a use of internal I2S DAC

What is the key combination that will switch to I2S DAC?

**Comment by 32teeth** [comment]
This feature is not exposed in the RetroESP32 firmware. We have also started migrating to [Ducalex Retro Go](https://github.com/ducalex/retro-go) and contributing there
