### ISSUE TITLE
Compilation error when running ./ota

### ISSUE THREAD

**Issue by Marcussy-lw** [retro-esp32/RetroESP32#107]
![Screenshot 2022-05-31 160007](https://user-images.githubusercontent.com/103623250/171123208-12dfac4d-1066-4505-9aca-3862dbea9a7f.png)

Some files seem to be missing in esp-idf leading to these compilation issues. I have already ran ./installer script and even tried to install the links within the script manually but still leads to these issues

**Comment by 32teeth** [comment]
> Hi there

Thanks for the notice

#### Attempt to build core
```
cd Scripts
source helpers/paths
cd ../Launchers/retro-esp32
make -j16
```

If the above works, follow the steps in `ota` script
```
cd Scripts
./ota
```

*Please Note*: We are not really building more on this platform and have instead moved to [ducalex's retro-go](https://github.com/ducalex/retro-go)
