### ISSUE TITLE
If I use RetroESP32-Hardware, which bootloader do I need to flash, I can't find it

### ISSUE THREAD

**Issue by hsinyuwang** [retro-esp32/RetroESP32#112]

**Comment by 32teeth** [comment]
[Retro ESP32](https://github.com/retro-esp32/RetroESP32/releases/tag/v.2.8-Overdue-Update-Including-ILI9342C-And-ST7789)

In the table
The direct link is [here](https://github.com/retro-esp32/RetroESP32/releases/tag/v.2.8-Overdue-Update-Including-ILI9342C-And-ST7789#:~:text=odroid%2Dgo.zip-,retro%2Desp.zip,-retro%2Desp.zip)
