### ISSUE TITLE
Odroid Go Firmware - Rotated Launcher

### ISSUE THREAD

**Issue by 32teeth** [retro-esp32/RetroESP32#16]
**Describe the bug**
Launcher is rotated in Odroid Go version

**Expected behavior**
Correct Orientation Needed

**Comment by NoraCodes** [comment]
Mine is still rotated :(

**Comment by cjanner** [comment]
> 
> 
> Mine is still rotated :(

Mine too. Going to create a new issue.

**Comment by cjanner** [comment]
New version is working: https://github.com/retro-esp32/RetroESP32/releases/download/v.1.3-PC-Engine-Frameskip/odroid-go.zip

**Comment by 32teeth** [comment]
Please See #34 for latest download
