### ISSUE TITLE
External DAC

### ISSUE THREAD

**Issue by ripper121** [retro-esp32/RetroESP32#18]
Please add an external DAC, the ESP32's build in DAC is to crappy to get a good sound out of it.
I would love to see it with external DAC, then I could listen to my mp3's <3

**Comment by 32teeth** [comment]
Thanks @ripper121 for the suggestion.

We are continuously exploring enhancement and PWM Audio (Standard on Odroid Go) to Stereo is one of them.

Currently we use an LM4875 from Texas Instruments

Some of the Digital Audio Convertors require Data and Clock as well as are power hungry

That said, we continue to research

**Comment by ripper121** [comment]
LM4875 is no DAC?! its a AMP...
Use the PCM5102a (DAC, needs no extra AMP) its great sound and compatible with all the Emulators.

**Comment by ripper121** [comment]
With LM4875 you will amplify the crappy sound from the ESP32 build in DAC! :(
