### ISSUE TITLE
Sound Glitch - When Entering In Game HUD

### ISSUE THREAD

**Issue by klundry** [retro-esp32/RetroESP32#21]
The sound from the game you are playing is stuck in a glitchy pause type state and sounds bad. Sound should probably be completely stopped when entering the menu screen.

**Comment by 32teeth** [comment]
Thanks @klundry 
Changed Title of Ticket for Project Board
This has been added to the project backlog

**Comment by 32teeth** [comment]
[Resolved in v.1.0.6-Sound-Fix Release](https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.0.6-Sound-Fix)
