### ISSUE TITLE
Add custom color pallette options for gameboy emulator

### ISSUE THREAD

**Issue by klundry** [retro-esp32/RetroESP32#27]
There are options to change the color pallette for gameboy in pelle7's launcher (amd maybe others?). It makes them look much nicer IMO and would be nice feature to have.

**Comment by 32teeth** [comment]
Ask and you shall receive!
![palette](https://user-images.githubusercontent.com/75797/66504859-1d5be100-ea98-11e9-885c-d8527e5fa7aa.gif)

https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.1.1-Gameboy-Palette
