### ISSUE TITLE
ROM listing is limited to 1024 items

### ISSUE THREAD

**Issue by EkriirkE** [retro-esp32/RetroESP32#30]
**Describe the bug**

**To Reproduce**
Any game system, fr which you have the "complete rom set"

arrows or start/select to page flip

the "end"

Game 1024/1024

**Expected behavior**
I expect the full romset to be listed and not truncated at 1024
nshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: ODROID-GO
 - OS: ESP32
 - Browser: RetroESP32
 - Version: v1.1.0

**Comment by 32teeth** [comment]
@EkriirkE 

Please try the latest firmware for the [Odroid Go](https://github.com/retro-esp32/RetroESP32/releases/download/v.1.3-PC-Engine-Frameskip/odroid-go.zip)

![file_nes](https://user-images.githubusercontent.com/75797/67765560-d6bc2f80-fa22-11e9-992d-62863f739512.gif)
![files_gb](https://user-images.githubusercontent.com/75797/67765561-d6bc2f80-fa22-11e9-94b9-94894afe5bce.gif)
![files_gbc](https://user-images.githubusercontent.com/75797/67765562-d6bc2f80-fa22-11e9-805a-90aaff39592e.gif)
![files_gg](https://user-images.githubusercontent.com/75797/67765564-d6bc2f80-fa22-11e9-96a4-86e635a6f145.gif)
