### ISSUE TITLE
Scree refresh rate

### ISSUE THREAD

**Issue by Superpuissant** [retro-esp32/RetroESP32#33]
Hi, I was wondering if it would be possible to improve screen refresh rate for all emulators? Maybe by implementing interlacing, like it is done in some other custom firmware for nes games?

**Comment by 32teeth** [comment]
@Superpuissant 

This is a great.

We focus on the [Launcher and the In Game Menu (HUD) ](https://github.com/retro-esp32/RetroESP32/tree/Software) as well as [Future Hardware Development](https://github.com/retro-esp32/RetroESP32/tree/Hardware)

The Emulators that are baked into our Launcher are actually pulled directly from the Emulator Creators themselves and are Submodules of our GitHub Repository

![Screen Shot 2019-10-16 at 9 45 06 AM](https://user-images.githubusercontent.com/75797/66925029-b55a4d00-eff9-11e9-8183-582eeee3de96.png)

What this means is that when we create new releases, we pull the latest version from the contributors.

If you have a Specific emulator, please let us know
