### ISSUE TITLE
Odroid Go Firmware - Rotated Launcher

### ISSUE THREAD

**Issue by cjanner** [retro-esp32/RetroESP32#34]
**Describe the bug**
Launcher is rotated 90° to the left in Odroid Go version. Also games are rotated and their image is scrambled.

**To Reproduce**
Running firmware version 20181001 and retro-esp32 version v.1.3.
Odroid-Go Rev. 0.1 20180518

**Screenshot**
![2019-10-29 09 22 42](https://user-images.githubusercontent.com/47459036/67750058-b6926d80-fa2e-11e9-9dcc-0008831a4779.jpg)

**Additional context**
Seems similar to https://github.com/retro-esp32/RetroESP32/issues/16.

**Comment by 32teeth** [comment]
This was entirely my fault. Compiling to different versions at the same time.

Please find i have updated the [Odroid Go](https://github.com/retro-esp32/RetroESP32/releases/download/v.1.3-PC-Engine-Frameskip/odroid-go.zip) firmware.

**Comment by cjanner** [comment]
Yes I can confirm. Now it is working.
Thanks
