### ISSUE TITLE
Brightness Control On Screen

### ISSUE THREAD

**Issue by SuperAngryPixel** [retro-esp32/RetroESP32#36]
**Is your feature request related to a problem? Please describe.**
Odroid Go Core software only has 4 levels of brightness control.
```10,33,66,100```

**Describe the solution you'd like**
With recent Retro ESP32 firmware updates, the volume setting was added to the on screen experience, please add this for brightness as well

**Describe alternatives you've considered**
N/A

**Additional context**
Is it possible to add more than 4 levels of brightness?

**Comment by 32teeth** [comment]
https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.5-Brightness-Control
