### ISSUE TITLE
When scrolling through emulators, "NO GAMES AVAILABLE" shows up randomly for everything and do not reappear until system reboot.

### ISSUE THREAD

**Issue by evan64** [retro-esp32/RetroESP32#38]
**Describe the bug**

**To Reproduce**
Scroll right on main menu.

**Expected behavior**
Games should show up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: v.1.6

**Comment by 32teeth** [comment]
Hi @evan64 
thanks for the Issue Log

This was happening previously, can you let me know which version of the firmware you are using?

[Can you try this on the latest](https://github.com/retro-esp32/RetroESP32/releases/latest)

**Comment by evan64** [comment]
It's happening on 1.6, the latest.

**Comment by 32teeth** [comment]
@evan64 we patched the latest release
if this is still happening, please post me a video or image of the sequence to reproduce

**Comment by metapy123** [comment]
I can reproduce this error. Here are the steps I took and they result in the error 100% of the time.
I have over 2500 games between systems and when I start going between consoles the games disappear when I get to the 2500 or so game. You can also have 800 games on one system go to the system then back to settings and repeat a few times for the error to appear.

So to replicate have Retro ESP count 2500+ games.

I noticed I went to NES games after settings after first boot. 864 NES games, back to settings, back to NES 864 games, back to settings, back to NES 779 games, then no games at all. I then deleted some games to get under 2500 total and then I could navigate to all the systems, but as soon as I hit 2500+ all games disappear even when the total games were under 2500.

I hope this helps and happy to do further testing as needed.

**Comment by 32teeth** [comment]
I am able to reproduce this.
Am setting this issue as higher priority.

Thanks

**Comment by 32teeth** [comment]
Fixed in [v.1.7](https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.7-Memory-Heap-Fix)
