### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by gbanfalvikl** [retro-esp32/RetroESP32#4]
Apologies if I missed this but I was wondering about a few things:

- Will it have some form of menu button, or are we going to have a button combination?

- Will it support a similar sleep mode to the Odroid GO?

- What's its estimated battery capacity?

**Comment by 32teeth** [comment]
##### Will it have some form of menu button, or are we going to have a button combination?
> Start + Select

##### Will it support a similar sleep mode to the Odroid GO?
> Depends on the FW you upload, but yes

##### What's its estimated battery capacity? 
> i have used 800mAh, 1200mAh, 2000mAh
