### ISSUE TITLE
Favorites and/or global game search

### ISSUE THREAD

**Issue by Brian2049** [retro-esp32/RetroESP32#40]
I have installed a lot of games for different systems. It would be helpful to be able to flag games as favourites to avoid scrolling to the, all the time and sometimes it is also not clear to what system they are belonging. Maybe an extra section called „Favourites“ conatining all the fav games and system info would solve this.

Another feature: Sometimes I know a title but not if it exists on the odroid-go or not and for which system (some titles exists on more than one system). A global search would be helpful here, too. Entering text should be possible with a virtual keyboard.

**Comment by 32teeth** [comment]
Thanks @Brian2049 

If you don't mind, i will close this ticket, I will split this into two Feature Requests

Feature Request:
- Favorites #41
- Search #42
