### ISSUE TITLE
NES Emulation Issues (Classic Dragon Warrior 4 issue)

### ISSUE THREAD

**Issue by derpman4k** [retro-esp32/RetroESP32#43]
I don't have much to say in terms of technical reasons why, but on the Odroid Go certain NES games (in this case Dragon Warrior 4) won't even boot. I'm not sure if this is an issue with the emulator core being used, or if a core can be changed to get around this, or if it's just a limitation of the hardware, or some optimization issues, or what have you (Being into emulators for a long time, I just know some games are always a pain to emulate). 

But a friend of mine has always wanted to run this on his Odroid Go and I figured I'd ask. Also curious if this will be an issue on the RetroESP32 hardware as well. 

Thanks!

**Comment by v666** [comment]
Same happens with Kick Master.

**Comment by 32teeth** [comment]
Tested in  [v.2.1](https://github.com/retro-esp32/RetroESP32/releases/tag/v.2.1-NES%2BLYNX)

**Comment by mrjoshw408** [comment]
Tested on 2.1 with US version of games:
Dragon Warrior 3
Dragon Warrior 4

I still get the grey screen and does not continue further.
