### ISSUE TITLE
The brightness indicator disappears when you switch menu pages

### ISSUE THREAD

**Issue by atylmo** [retro-esp32/RetroESP32#45]
**Describe the bug**
When you first turn on the ODROID GO, there is an indicator at the top right that shows the brightness level. However, moving to another menu makes this indicator disappear in every other menu except Settings. It appears there.

**To Reproduce**
1. Turn on the ODROID GO from off
2. Notice the brightness indicator in the top right next to the battery and volume indicators.
3. Switch menu pages with left and right. The brightness indicator goes away.
4. If you go into the Settings menu the indicator will reappear, but it disappears again when you switch menus.

**Expected behavior**
The brightness indicator should stay on-screen the same way that the battery and volume indicators do.

**Comment by 32teeth** [comment]
Fixed in [v.1.7](https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.7-Memory-Heap-Fix)
