### ISSUE TITLE
System reebots when selecting Sega Master System

### ISSUE THREAD

**Issue by EduOrtegaDEV** [retro-esp32/RetroESP32#47]
**Describe the bug**
I don't have any game for the Sega Game Gear System and when I'm trying to select this system the Odroid Reboots.

**To Reproduce**
1. Go to Sega Game Gear
2. See error

**Screenshots**
Check the video with the problem here:

https://drive.google.com/open?id=1uSRk8C_VuYwg9vrqcMAM9YWtMr5Mz7p2

**Comment by v666** [comment]
I think that happens with all emulators that don't have any roms available. Same happened to me with PC Engine.

**Comment by EduOrtegaDEV** [comment]
I have other systems with no roms at all as you can see in the video and works perfectly... Gonna add some roms to see if that's the problem...

**Comment by shockdesign** [comment]
This sounds familiar to the issue I was having @32teeth 

@EduardoOrtegaME What version of the firmware are you running?

**Comment by EduOrtegaDEV** [comment]
I’m using Version 1 Build 6 (Version 1.6)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by 32teeth** [comment]
Fixed in [v.1.7](https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.7-Memory-Heap-Fix)
