### ISSUE TITLE
Odd UI Settings screen behavior after selecting color Themes, and then pressing left or right keypad.

### ISSUE THREAD

**Issue by v666** [retro-esp32/RetroESP32#48]
It looks like Settings screen gets stuck in Color theme setting mode, after you select "THEMES" option and then press left or right to move along the different console emulation options.

1. Start device, RetroESP32 is launched.
2. "SETTINGS" screen is displayed - Themes, colored icons, volume and brightness options are displayed - Themes is selected by default.
3. Select "THEMES" by pressing A button -> List of available colors is displayed.
4. Press keypad right or left - left takes you to PC Engine console, right to NES console.
5. Go back to Settings screen, by pressing the keypad in the opposite direction you pressed in step 4.
6. "SETTINGS" screen is displayed - Themes, colored icons, volume and brightness options are displayed - Themes is selected by default.

From this point, depending on the button pressed, different things can happen: 

7.A Press keypad down - List of available colors from "THEMES" option is displayed - you can still see the enable colored icons, volume bar and brightness bar options displayed.
7.B Press A Button - The last default color selected in the available colors list will be set as the current Color theme. The list of available colors will be displayed.

Expected behavior / Proposal:
I think that after entering into the "THEMES" option, having the list of available colors displayed, user should not be able to move between emulation consoles.
Any other button other than UP, DOWN or A, should just cancel the operation and return User to Settings Screen.
Or better yet - pressing keypad up or left, will select next color option up in the list, and pressing down or right, will select next color option down in the list - B would return User to the Settings Screen.

**Comment by 32teeth** [comment]
Fixed in [v.1.7](https://github.com/retro-esp32/RetroESP32/releases/tag/v.1.7-Memory-Heap-Fix)
