### ISSUE TITLE
gb/gbc emulator volume doesn't toggle steps, only on/off

### ISSUE THREAD

**Issue by alcuin2k** [retro-esp32/RetroESP32#50]
gb/gbc emulator volume doesn't toggle steps, only on/off.  Volume stepping in main menu works, and volume stepping in nes emulator works, but in gb/gbc games only toggles on and off.  Tried sml3, tetris, warioland3 on gb/gbc,

**Comment by 32teeth** [comment]
@alcuin2k 
Since GB/GBC emulator uses Super-Go-Play

## Actions
> List of Commands

* [Volume] - Toggle Sound On/Off
* [Volume + UP] - Volume Increase
* [Volume + Down] - Volume Decrease
