### ISSUE TITLE
Newest release games not saving

### ISSUE THREAD

**Issue by SleepWalker380** [retro-esp32/RetroESP32#51]
**Describe the bug**
When an NES rom is running, and you try to save, or overwrite a save, the save screen comes up, the progress bar moves across, and the system freezes, save never completes, unit becomes unresponsive, when restarted the game continues from the previous save, but not the save that was just attempted.

**To Reproduce**
1. Go to 'Any NES rom'
2. Click on 'Save or Overwrite Save'

**Expected behavior**
Unit will freeze, save will not complete

**Additional context**
Fimware fully updated

**Comment by 32teeth** [comment]
Firmware was updated a few hours ago
Please retry 1.9
