### ISSUE TITLE
where to get the bootloader for the retro esp32 board ? i flashed my board with wrong bootloader .. and now the screen is the wrong way ;(

### ISSUE THREAD

**Issue by lastclass74** [retro-esp32/RetroESP32#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 32teeth** [comment]
The are located in the [releases](https://github.com/retro-esp32/RetroESP32/releases) section

[zip file](https://github.com/retro-esp32/RetroESP32/releases/download/v.2.0-Cover-Art-Option/retro-esp.zip)

[direct download](https://github.com/retro-esp32/RetroESP32/blob/Software/Firmware/Releases/retro-esp/Retro%20ESP32.fw?raw=true)

Now, to restore it

1. add the above ```.fw``` file onto the sd card
2. insert sd card
3. power on _while_ holding **B**
4. you will now be back in the core firmware
5. navigate to the new firmware and flash it

as a tip
restarting while holding B will always get you back to the core firmware

**Comment by lastclass74** [comment]
thx but its the base firmware for retro esp32.. can i just you odroid base firmware  ?

thx for the help

**Comment by 32teeth** [comment]
Not sure i understand

The Retro ESP32 comes with [Retro Odroid Go Firmware](https://github.com/retro-esp32/Retro-Odroid-Go-Firmware) Installed

Retro ESP32 is a firmware you load on top

If you are looking to use the standard Odroid Go Firmware from Crash, you can find it in the Software branch of the repo

**Comment by 32teeth** [comment]
Oh, NVM, you have an Odroid Go?
Yes, the release page always has both versions, just download the right one
 
## Odroid Go **<-----  THIS IS WHAT YOU HAVE**
> 2.4" Display

Launcher to the **Odroid Go** for the ILI9341 LCD Driver
#### [odroid-go.zip](https://github.com/retro-esp32/RetroESP32/releases/download/v.2.0-Cover-Art-Option/odroid-go.zip)

## Retro ESP32
> 2.6" Display

Launcher to the **Retro ESP32** *(Game Boy Pocket)* ILI9342 LCD Drive
#### [retro-esp.zip](https://github.com/retro-esp32/RetroESP32/releases/download/v.2.0-Cover-Art-Option/retro-esp.zip)

**Comment by lastclass74** [comment]
no im sorry if im hard to understand..
i need Retro Odroid Go Firmware (.img) for the retro esp32 - 2.6" Display ... 

thx

**Comment by 32teeth** [comment]
If you where able to ```flash``` your device using USB

[Go here](https://github.com/retro-esp32/Retro-Odroid-Go-Firmware)

1. clone repo
2. cd into ```Firmware``` folder
3. Run ```make menuconfig```
4. change your settings appropriately
5. go to ```Scripts``` folder
6. run ```./ota```

**Comment by lastclass74** [comment]
thats the one i looked for ... now works 100 % thx ...

hope to see c64 soon ;)
