### ISSUE TITLE
Atari Lynx Cover Art not showing in v2.1

### ISSUE THREAD

**Issue by ultrasteveg** [retro-esp32/RetroESP32#57]
**Describe the bug**
Lynx cover art not being displayed

**To Reproduce**
1. Download romart.zip
2. Copy contents to relevant folders on SD Card
3. Open a game in Lynx
4. No Preview

**Expected behavior**
Lynx cover art should be displayed as with other emulators

**Additional context**
I've made sure filenames are the same. I've used known good art from another emulator in place of a Lynx game (ensuring correct filename) and have tried creating new art online. None work.

**Comment by 32teeth** [comment]
Thanks @ultrasteveg 
We have found the bug and documented it for now.

We will release a fix in the next release

### Hot Fix
1. eject your sd card
2. navigate to ```romart``` folder
3. copy the ```lynx``` folder
4. paste
5. rename new folder to ```lnx```

**Note:** for the time being keep both ```lynx``` and ```lnx``` folders in ```romart```
