### ISSUE TITLE
Rolling Thunder NES Emulation Issue

### ISSUE THREAD

**Issue by ultrasteveg** [retro-esp32/RetroESP32#58]
Using v2.2

**Describe the bug**
Screen rolls (oh, the irony!) on Rolling Thunder for NES. This does not happen with the emulator included in Go-Play.

**To Reproduce**
1. Run RollingThunder (U)
2. Immediately upon loading screen will roll.

**Expected behavior**
Screen should not roll.

**Screenshots**
Video here: https://drive.google.com/open?id=1vGcSvD_rD2SxsloxEapk4tmDiTln8E6b

**Comment by 32teeth** [comment]
Unable to reproduce

**Comment by ultrasteveg** [comment]
Using v2.5 the issue still exists for the USA ROM. Japan ROM will load, then on-screen message of "The emulator crashed" with an OK prompt.
