### ISSUE TITLE
On retro esp32 (gameboy pocket), the volume of nes emulator is small.

### ISSUE THREAD

**Issue by atsu73** [retro-esp32/RetroESP32#64]
Volume is small even if Volume Wheel is maximized.

On nes emulator (playing) ,
It seems that the default volume can be changed with the GPIO10(?) switch on the back.
It is fine to change the default value (4/8) to the maximum (8/8), but I will not be able to quit the emulator.

I want to change the default value to the maximum volume.

gb, gbc emulator is just right.

**Comment by 32teeth** [comment]
Hi @atsu73 

Thanks for this.
It has been mentioned before and expect a new release before end of week.

**Comment by atsu73** [comment]
I confirmed that it improved in v2.3.
Thank you!
