### ISSUE TITLE
Visibility of selected text in menus is not very good

### ISSUE THREAD

**Issue by klundry** [retro-esp32/RetroESP32#67]
Currently selected text in menus is not very obvious. Under some lighting it is extremely hard to differentiate the highlighted text from the rest. 

I have a couple of ideas for making the selected menu item more obvious.

Something as simple as adding a > character in front of the text that is currently selected could work. Or you could make it even more noticeable by having a box around the selected text and inverting the colors.

**Comment by 32teeth** [comment]
Resolved with better contrast in 2.4
