### ISSUE TITLE
Upload Retro-ESP to blank ESP32?

### ISSUE THREAD

**Issue by cctvfm** [retro-esp32/RetroESP32#75]
Could you give a brief how-to on uploading firmware to a fresh ESP32? I'd love to play around with this but not sure how to start.

Thanks

**Comment by 32teeth** [comment]
Hi @cctvfm 

We have been working on a 'from scratch' documentation [DIY.md](https://github.com/retro-esp32/RetroESP32/blob/master/DIY.md)

TL;DR

```
git clone -b master --single-branch git@github.com:retro-esp32/RetroESP32.git --recursive
cd RetroESP32
git submodule update --init --recursive
git submodule foreach git pull origin master
chmod -R 777 Scripts
cd Scripts
./ota
```

Follow the onscreen prompts
* If you are using a 2.4" ILI9341 choose Odroid-Go when it asks
* If you are using a 2.6" ILI9342 choose RetroESP32 instead
