### ISSUE TITLE
link to documentation is missed

### ISSUE THREAD

**Issue by fizarum** [retro-esp32/RetroESP32#78]
**Describe the bug**
On page: https://www.tindie.com/products/handheld-gaming/retro-esp32/#product-description
you can see section: "Design Files" which is broken (leads to non-existing: https://github.com/retro-esp32/RetroESP32/tree/Hardware)

**To Reproduce**
1. Go to https://www.tindie.com/products/handheld-gaming/retro-esp32/#product-description
2. Click on "Design Files" section
4. See 404 github page

**Expected behavior**
working link to hardware repo/branch/section

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: any modern
 - Browser chrome
 - Version n/a

**Additional context**
Looks like the entire "Hardware" section has been removed and I'd like to ask if it possible to return it back - I'm going to build (or try at least) hardware part from scratch

**Comment by 32teeth** [comment]
Thank @fizarum 
This happened when we consolidated branches

a new repo now exists for [design](https://github.com/retro-esp32/RetroESP32-Design-Files)

thank you for bringing this to our attention
