### ISSUE TITLE
Roms fail to load after reaching 50 items on recently played list

### ISSUE THREAD

**Issue by klundry** [retro-esp32/RetroESP32#82]
Roms fail to load once you go over 50 games in your recents list with the caveat that it WILL load if it is already in your recents list. I believe it is related to #59 

There is a clear recents option but would it be possible to just drop the oldest item off the list to prevent this?

**Comment by 32teeth** [comment]
@klundry thanks, we will look into this for the next release.
Much Appreciated insight

**Comment by 32teeth** [comment]
Closed as of latest release

**Comment by klundry** [comment]
I'm on the latest release but ran into this issue again with the recents list.

**Comment by EugeneAndruszczenko** [comment]
We are aware of this. And working on it.
For the time being you can easily just go to the 'recents' and 'clear recents' and your good for another 50 games :(
Sorry i know it's a pain in the ass, but we will have a fix up soon

**Comment by klundry** [comment]
OK, cool. Yeah, its not too big a deal just thought I would mention it since the issue was closed.
