### ISSUE TITLE
Sega Master System can't save

### ISSUE THREAD

**Issue by Pitel** [retro-esp32/RetroESP32#87]
**Describe the bug**
Can't save a game in SMS games

**To Reproduce**
1. Starts SMS game
2. Press menu button
3. Select SAVE GAME
4. Progress bar appeats, gets almost to the end
5. :boom:

**Expected behavior**
It saves and return to game

**Additional context**
* Loading games saved in previous versions works.
* The save file is NOT created, I can't load it after restart.
* Saving in other emulators works.

**Comment by 32teeth** [comment]
See lates release

**Comment by Pitel** [comment]
@32teeth The issue is back, and maybe even worse! I've noticed I can't save games on both SMS ang GG. 😿

v2.8 has this bug, 2.7 is ok.
