### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by n1trux** [retro-esp32/RetroESP32#89]
Would be nice if you could write a manual on how to use this.

I wanted to gift this to a kid and had no time to explain :(

**Comment by 32teeth** [comment]
Thank you for the feedback.

Unfortunately We currently do not have any stock on these items and thus want be able to provide you any packaging or printed material.

If you are looking for additional information and have fully reviewed the provided direction in our Wikipedia section, please reference the original Odroid Go documentation for more technical details

We appreciate your patronage

**Comment by n1trux** [comment]
well, at least a small manual on how to use this "for dummies" would be cool for the README.md. This has nothing to do with the original Odroid hardware, because it's the RetroESP32 menu where the documentation is missing.

E.g.:

> ← / → : Change tabs (console, settings select)
> ↑ / ↓ : select game
> A : open game / open game menu
> B : back
> ≡: menu / back to main menu
> 🔈: change ingame settings (Volume etc.)
> SELECT / START: scroll through menu pages

I don't want a package or a printed manual, I just wanted to gift my old ODROID GO with your firmware to a 9yo kid ;)

For anyone reading this: the ODROID GO can still be bought from the German vendor Pollin.de: https://www.pollin.de/p/odroid-go-mobile-spielekonsole-kit-810887

Is there a way to create screenshots from the system to enrich a manual with them? E.g. "this is the main menu, you can do X and Y here".

Thank you for this awesome firmware, it truly is the best working and maintained firmware for the ODROID GO. It's a joy to use and I guess the kid I'm gifting this to will have a lot of fun with it :)

**Comment by 32teeth** [comment]
https://github.com/retro-esp32/RetroESP32/blob/master/USAGE.md
