### ISSUE TITLE
Emulator Crashes if Target File is Blank

### ISSUE THREAD

**Issue by 32teeth** [retro-esp32/RetroESP32#9]
**Describe the bug**
```odroid_settings_RomFilePath_get()``` will return an empty string if not set from Retro ESP32 Launcher

**To Reproduce**
This relates to [Ability to Navigate Sub Folders in ROM Directories](https://github.com/retro-esp32/RetroESP32/issues/8)

**Expected behavior**
If ```odroid_settings_RomFilePath_get()``` is true but blank, return to Retro ESP32 Launcher in last known State

**Additional context**
Should be fixed when [Ability to Navigate Sub Folders in ROM Directories](https://github.com/retro-esp32/RetroESP32/issues/8) is implemented

**Comment by shockdesign** [comment]
Noticed it crashes if there aren't any ROMs in a folder... seems to need at least one ROM in each folder.
